query Articles($category: String) {
  articles(where: { category: { slug: $category } }) {
    id,
    title,
    cover {
      formats
    },
    category {
      title,
      slug
    },
    slug
  }
}
